### ISSUE TITLE
Orbit b-hyve compatibility

### ISSUE THREAD

**Issue by mlee12382** [petergridge/Irrigation-V5#137]
Hello, I am trying to set up your irrigation programs and it doesn't seem to be fully compatible with the [Orbit b-hyve controller integration](https://github.com/sebr/bhyve-home-assistant). It works partially but only triggers the default manual watering runtime instead of using the programmed runtimes. 

It looks like there's a [fairly easy way](https://github.com/sebr/bhyve-home-assistant?tab=readme-ov-file#zone-switch) to adjust it through commands with the b-hyve integration if I were to set up automations manually but that's tedious and not as clean as using an integration like yours. 

Just as an example I am able to manually do the following which overrides the default 5 minute manual run:
```
alias: 'Orbit BHyve Integration: start_watering'
description: ''
trigger:
  - platform: time
    at: '06:00:00'
condition: []
action:
  - service: bhyve.start_watering
    data:
      entity_id: switch.north_planters_zone
      minutes: 10
  - delay: '00:10:30'
  - service: bhyve.start_watering
    data:
      entity_id: switch.middle_planters_zone
      minutes: 10
  - delay: '00:10:30'
  - service: bhyve.start_watering
    data:
      entity_id: switch.south_planters_zone
      minutes: 10
  - delay: '00:10:30'
mode: single
```

I found this solution in [this thread](https://community.home-assistant.io/t/integration-with-orbit-b-hyve-irrigation-system/39688/296?page=15). Is there a way to modify the functions for your integration on my end? Or would you be able to add compatibility on your end like you did for RainBird?

**Comment by petergridge** [comment]
On my first look at this I don't see any issues integrating the b-hyve api calls into this integration. I will try to get an update out in the next week or so. I will send an update when a Beta is available for you to test.

**Comment by mlee12382** [comment]
Awesome! Thanks 😀

**Comment by petergridge** [comment]
Hi V2025.04.01 has been released with a Beta of this option I cannot test the integration fully. Please let me know if this works or provided the errors/problems if it doesn't

**Comment by mlee12382** [comment]
It doesn't seem to start the program. It appears to just hang with the timers not counting down. Also the run time display for the cards shows as seconds now instead of minutes.

![Image](https://github.com/user-attachments/assets/e86ddfcc-4ef1-4397-96c9-020e13d4d1d1)
[config_entry-irrigationprogram-01JQFQ1VNWQPPD43WNTPQKQGCD.json](https://github.com/user-attachments/files/19716501/config_entry-irrigationprogram-01JQFQ1VNWQPPD43WNTPQKQGCD.json)

**Comment by petergridge** [comment]
Thanks, you can change the run time back to minutes in the advanced settings, missed the default on that on in the upgrade sorry.

Can you send me the log entry, there should be errors from the irrigation program that will highlight the issue calling the service. I cannot replicate on my end as I do not use B-Hyve

**Comment by mlee12382** [comment]
```
Logger: homeassistant
Source: core.py:2759
First occurred: 9:36:00 PM (1 occurrences)
Last logged: 9:36:00 PM
Error doing job: Task exception was never retrieved (None)

Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/zone.py", line 798, in async_turn_on_from_program
    await self.async_solenoid_turn_on()
  File "/config/custom_components/irrigationprogram/zone.py", line 608, in async_solenoid_turn_on
    await self.hass.services.async_call(
    ...<6 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/core.py", line 2759, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 382, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['duration']
```

Even manually setting it to minutes instead of seconds it is showing as seconds on the cards still. The remaining time on the main program section looks correctly formatted as minutes but under the zones it's showing as seconds. It looks like maybe that's part of the error?

**Comment by petergridge** [comment]
New version 2025.04.02. fixed the minute second issue, poor testing on my part, sorry. I think I have fixed the service call issue aswell.

**Comment by mlee12382** [comment]
That appears to be working now. Thanks a bunch for adding the functionality and troubleshooting the errors for me. It's nice to have everything all in one place.

One thing I noticed and I'm not sure if it's by design or not, but when you set the timer max when settup up the program if you set a single zone to that max nothing else runs as it expires the program timer. I have to set the maximum to n times what I want available for that program where n is the number of zones. Is this as intended? I had initially thought it was a max per zone thing.

**Comment by petergridge** [comment]
The max runtime is only used to set the max value on the input for watering time. So I am not sure why the max is impacting.

In my testing I set the max for 2 minutes, two zones, both ran sequentially as expected and the program timer is 4 minutes.

Can you send me a screenshot of your advanced settings on the program

**Comment by mlee12382** [comment]
Ahh, never mind. It seems it may have just been a communication issue with one of the devices. I had the max set for 60 minutes and had 3 zones at 30 minutes each and the third device didn't run. I just retested and it looks to be working correctly.

Thanks again!

**Comment by mlee12382** [comment]
Nope my mistake the issue is still there. I set the max to 10min on a test program with 3 zones. I set the first 2 zones to 10 minutes and the 3rd to 5 minutes. It showed a 25min program timer when it started and ran the first zone at 10minutes and then instead of going to the next zone it just ended the program. It didn't output any errors in the logs that I can see.

[config_entry-irrigationprogram-01JRP4PM02GJAN2WTQ3EQVZ2A5.json](https://github.com/user-attachments/files/19722350/config_entry-irrigationprogram-01JRP4PM02GJAN2WTQ3EQVZ2A5.json)

![Image](https://github.com/user-attachments/assets/e79f43f0-c5dd-47ec-ac0a-bcd8a5910b05)
![Image](https://github.com/user-attachments/assets/546d07c0-c48c-4584-9f42-7cccb2493cf5)

**Comment by mlee12382** [comment]
This is really weird. Sometimes it looks like it's working correctly and other times it seems to skip zones. Not sure why. There's no apparent errors in the logs and I can manually command the valves open and closed. Gonna have to keep an eye on it and see if I find anything that stands out as being the cause. I will keep you updated if I find anything. Or if you have any ideas on something to check let me know.

**Comment by petergridge** [comment]
Can you try with a +10sec zone transition.

**Comment by petergridge** [comment]
It looks like I am passing the duration for the service as seconds not minutes, I will round up to the nearest minute to determine the run time.

**Comment by mlee12382** [comment]
The devices seem to trigger and then immediately shut back off. Any ideas?

**Comment by petergridge** [comment]
can you monitor the events

<img width="535" alt="Image" src="https://github.com/user-attachments/assets/71488b1f-e573-4d27-b811-7be312278069" />

That may give me a clue

**Comment by petergridge** [comment]
Can you also use the bhyve.start_watering action run from the developer tools interface and send me the parameters that are working for you.

**Comment by mlee12382** [comment]
I was doing my tests with zigbee valves. I can try with the b-hyve also, not sure if the results will be any different.

Event 0
```
event_type: irrigation_event
data:
  action: program_turned_on
  device_id: switch.test
  scheduled: true
  program: Test
origin: LOCAL
time_fired: "2025-04-13T22:16:00.005746+00:00"
context:
  id: 01JRRKJJ85T3AC8GYQMVNSPZYY
  parent_id: null
  user_id: null
```

Event 1
```
event_type: irrigation_event
data:
  action: zone_turned_on
  device_id: valve.bedroom_flower_beds
  pump: null
  scheduled: true
  zone: Bedroom Flower Beds
  runtime: 120
  water: 120
  wait: 0
  repeat: 1
origin: LOCAL
time_fired: "2025-04-13T22:16:00.016359+00:00"
context:
  id: 01JRRKJJ8GXDKD4RR0GAGRV4GQ
  parent_id: null
  user_id: null
```

Event 2
```
event_type: irrigation_event
data:
  action: zone_turned_off
  device_id: valve.bedroom_flower_beds
  zone: Bedroom Flower Beds
  state: aborted
origin: LOCAL
time_fired: "2025-04-13T22:16:05.024218+00:00"
context:
  id: 01JRRKJQ50HBBDSBG57ZJHW39S
  parent_id: null
  user_id: null
```

Event 3
```
event_type: irrigation_event
data:
  action: zone_turned_on
  device_id: valve.living_room_flower_beds
  pump: null
  scheduled: true
  zone: Living Room Flower Beds
  runtime: 120
  water: 120
  wait: 0
  repeat: 1
origin: LOCAL
time_fired: "2025-04-13T22:16:16.043743+00:00"
context:
  id: 01JRRKK1XB9DG08P9XD9EJ0XJS
  parent_id: null
  user_id: null
```

Event 4
```
event_type: irrigation_event
data:
  action: zone_turned_off
  device_id: valve.living_room_flower_beds
  zone: Living Room Flower Beds
  state: aborted
origin: LOCAL
time_fired: "2025-04-13T22:16:21.055929+00:00"
context:
  id: 01JRRKK6SZ1EW3FGTGYXBHY2YQ
  parent_id: null
  user_id: null
```

Event 5
```
event_type: irrigation_event
data:
  action: zone_turned_on
  device_id: valve.trellis_planters
  pump: null
  scheduled: true
  zone: Trellis Planters
  runtime: 120
  water: 120
  wait: 0
  repeat: 1
origin: LOCAL
time_fired: "2025-04-13T22:16:32.082852+00:00"
context:
  id: 01JRRKKHJJF2SZ65PRNHS5GX1C
  parent_id: null
  user_id: null
```

Event 6
```
event_type: irrigation_event
data:
  action: zone_turned_off
  device_id: valve.trellis_planters
  zone: Trellis Planters
  state: aborted
origin: LOCAL
time_fired: "2025-04-13T22:18:34.342134+00:00"
context:
  id: 01JRRKQ8Z66XTXYHY43VB8QQEG
  parent_id: null
  user_id: null
```

Event 7
```
event_type: irrigation_event
data:
  action: zone_turned_off
  device_id: valve.trellis_planters
  zone: Trellis Planters
  state: aborted
origin: LOCAL
time_fired: "2025-04-13T22:18:34.342134+00:00"
context:
  id: 01JRRKQ8Z66XTXYHY43VB8QQEG
  parent_id: null
  user_id: null
```

**Comment by petergridge** [comment]
Ok, your zigbee valves are different, if the device is not updating the state to on then the integration will abort the process as it cannot determine when to turn off the again so it will abort.

There is a 5 second wait before it aborts to allow the device to update HA.

Are you still experiencing issues with the BHYVE solenoids?

**Comment by mlee12382** [comment]
I tested the bhyve devices and they seem to work ok. Is there a way to increase the timeout on the zigbee devices? They work fine with a standard automation.

**Comment by petergridge** [comment]
How long do they take to transition state from off to on? I am assuming this is the issue but it would be good to confirm.

How are they reporting the state? on/off or open/closed?

You can change the latency on your local build by going to the const.py file in the custom component and updating the CONST_LATENCY = 5 to a higher value and restarting HA. This will stay until you upgrade to a new version.

Are you using ZHA or zigbee2mqtt for your zigbee devices? ZHA is sometimes not as uptodate, it may be worthwhile looking for a quirk that improves the response for your valves.
